import{a as E,S as b,i as m}from"./assets/vendor-527658dd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();async function f(r,t){const e="https://pixabay.com/api/",o={key:"42263617-81d7156b9f7b88cd7b1016c2a",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t};return(await E.get(e,{params:o})).data}function w(r){const{largeImageURL:t,webformatURL:l,tags:a,likes:e,views:o,comments:s,downloads:L}=r;return`<li class="gallery-item" >
    <a class="gallery-link" href="${t}">
      <img
        class="gallery-image"
        src="${l}"
        alt="${a}"
      />
    </a>
    <div class="item-text">
    <p><strong>Likes:</strong> ${e}</p>
    <p><strong>Views:</strong> ${o}</p>
    <p><strong>Comments:</strong> ${s}</p>
    <p><strong>Downloads:</strong> ${L}</p>
    </div>
  </li>`}function S(r){return r.map(w).join("")}const n={formEl:document.querySelector(".form"),loadEl:document.querySelector(".loader"),GalleryEl:document.querySelector(".gallery"),loadMore:document.querySelector(".js-btn-load")};let c,i,u;n.formEl.addEventListener("submit",M);n.loadMore.addEventListener("click",q);const h=()=>{n.loadEl.classList.remove("hidden")},d=()=>{n.loadEl.classList.add("hidden")};async function M(r){if(r.preventDefault(),h(),c=r.target.elements.query.value.trim(),!c){n.GalleryEl.innerHTML="",g(),d();return}i=1;try{const t=await f(c,i);if(u=Math.ceil(t.totalHits/15),t.hits.length===0){r.target.reset(),P(),d();return}else n.GalleryEl.innerHTML="",p(t.hits)}catch{g(),u=0,n.GalleryEl.innerHTML=""}d(),y(),r.target.reset()}async function q(){i+=1,h();const r=await f(c,i);p(r.hits),d(),y();const t=n.GalleryEl.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:t*2})}const v=new b(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.8,scaleImageToRatio:!0});function p(r){const t=S(r);n.GalleryEl.insertAdjacentHTML("beforeend",t),v.refresh()}function y(){i>=u?($(),R()):T()}function g(){m.error({message:"Please enter a search query.",position:"topRight"})}function P(){m.error({backgroundColor:"#ff0000",position:"topRight",maxWidth:500,message:"Sorry, there are no images matching your search query. Please try again!"})}function R(){m.error({backgroundColor:"#dc143c",message:"We're sorry, but you've reached the end of search results",position:"bottomCenter"})}function T(){n.loadMore.classList.remove("hidden")}function $(){n.loadMore.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
